#!/bin/bash
# This script starts Kepler.
# Run with -h to see all command-line options.
# This script is auto-generated by the 'ant make-startup-script' command.

CUR_DIR=`pwd`
SCRIPT="$0"
if [ -L "$SCRIPT" ]
then
  SCRIPT=$(readlink "$SCRIPT")
fi
SCRIPT_DIR=$(dirname "$SCRIPT")
cd "$SCRIPT_DIR"
java -classpath build-area/lib/ant.jar:kepler.jar org.kepler.build.runner.Kepler  "$@"
cd "$CUR_DIR"
