@echo off
REM This script starts Kepler.
REM Run with -h to see all command-line options.
REM This script is auto-generated by the 'ant make-startup-script' command.

java -classpath "%~dp0\build-area\lib\ant.jar";"%~dp0\kepler.jar" org.kepler.build.runner.Kepler UseModuleManager %*
